### ISSUE TITLE
Alternatives?

### ISSUE THREAD

**Issue by anurbol** [staltz/prevent-global-this#3]
It would be much better if readme showed some examples of what could *really* be used instead of globalThis. Just rejecting something without suggesting another option is never good. The current state of this repo feels like it just makes the life harder for the TC39 committee.

**Comment by josepot** [comment]
Hi @anurbol ,

I _think_ that the right place to propose alternative names is in the corresponding tc39 repo, which BTW is the first link of the readme. The second one, is a link to [the issue/discussion](https://github.com/tc39/proposal-global/issues/31) that IMHO has motivated the creation of this repo. In there you will find **lots** of alternatives that different developers have proposed. The problem is that **all** of them have been "refuted" with arguments that many of us find dubious at best.

For instance, my favorite alternative is `globalContext` and the argument for refuting it was:

> "globalContext" is interesting, but "context" isn't a commonly used term, so I'd find that confusing as well

:roll_eyes: 

Anyhow, what I'm trying to say is that maybe you are missing the point of this repo, because "making the life harder for the TC39 commitee" is IMHO pretty much what this repo is about (for this concrete topic). Also, I would like to suggest that you re-read the [Disclaimers](https://github.com/staltz/prevent-global-this#disclaimers) section and the content of its links :smile:

**Comment by anurbol** [comment]
Hi! I did read all the links, including [this](https://github.com/tc39/proposal-global/issues/32). And I personally left with the impression that tc39 made a really big effort in picking the final identifier. I also feel they made a good enough reasoning on every single alternative. You may be right, I just wrote what I feel about this repo, really may be disappointing for a tc39 member to see activities like these happening without a good enough reasoning, i.e. suggesting real alternatives.
